### ISSUE TITLE
fromString method accepts invalid strings

### ISSUE THREAD

**Issue by Philippus** [47degrees/memeid#134]
Because the `java.util.fromString`-method is used it suffers from the same problem as that one. It is far too accepting of invalid strings (that are not RFC compliant), java 9 improved a bit on it compared to java 8 but it is still not good enough.

Try for example: `UUID.fromString("1-1-1-1-1")` or `UUID.fromString("00112233-4455-6677-8899-aabbccddee")`

In akka-http we first validate the string to see if it complies with this regex before calling java.util.fromString:
`[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}`

if you need more speed for parsing the string you can look at jsoniter-scala or fast-uuid.

**Comment by alejandrohdezma** [comment]
Hi @Philippus!

Thank you very much for your contribution ❤️ 

Eventually, we would want to find a more performant solution, as you suggested, but in the meantime, this will be fine.

Thank you!
