### ISSUE TITLE
Extract UUID construction to a Java-only library

### ISSUE THREAD

**Issue by purrgrammer** [47degrees/memeid#69]
We can publish and depend on a Java-only version that contains the UUID creation logic, then implement the type hierarchy for UUIDs in Scala/Kotlin in a idiomatic way for each language. I'd keep the tests in Scala for the Java library if we can depend on Scala only for testing, since they are so much nicer to write/read than Java.

**Comment by alejandrohdezma** [comment]
This isn't finished yet... still missing a couple constructors
