### ISSUE TITLE
Use a diferent top-level namespace for JVM lang integrations

### ISSUE THREAD

**Issue by purrgrammer** [47degrees/memeid#75]
In order to be able to import `<namespace>.UUID` and not clash with the Java `memeid.UUID`

**Comment by purrgrammer** [comment]
Not sure how it is in Kotlin, but in scala when we create a `memeid.scala` package it interferes with the top-level `scala` namespace of the stdlib. Also using the same `memeid` package as in the Java part doesn't allow us to have a custom UUID type and static methods.

 /cc @nomisrev

**Comment by nomisRev** [comment]
That is not allowed in Kotlin either, and I wouldn't recommend it either.
So I am in favor of your suggested change @purrgrammer.
